version: '3.7'

services:
  pim-db:
    image: postgres
    container_name: pim-db
    volumes:
      - pim-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pim
    ports:
      - "5432:5432"
    expose:
      - "5432"
  om-db:
    image: postgres
    container_name: om-db
    volumes:
      - om-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=om
    ports:
#      - "5432:5432"
      - "5433:5432"
    expose:
#      - "5432"
      - "5433"
  pim-service:
    image: pim-service
    container_name: pim-service
    build:
      context: ./pim-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
        - spring.application.name=pim-service
        - spring.application.port=8080
        - spring.datasource.url=jdbc:postgresql://pim-db:5432/pim
        - spring.datasource.username=admin
        - spring.datasource.password=admin
    depends_on:
      - pim-db
  om-service:
    image: om-service
    container_name: om-service
    build:
      context: ./om-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - spring.application.name=om-service
      - spring.application.port=8081
      - spring.datasource.url=jdbc:postgresql://om-db:5432/om
      - spring.datasource.username=admin
      - spring.datasource.password=admin

    depends_on:
      - om-db
volumes:
  pim-db-volume:
  om-db-volume: